// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCofDK6y-2s1qjBPGuwLSW299C2oNT4OQ',
    appId: '1:750761744273:web:d0467a011bdf2140926c30',
    messagingSenderId: '750761744273',
    projectId: 'fixcity-1a1a1a',
    authDomain: 'fixcity-1a1a1a.firebaseapp.com',
    storageBucket: 'fixcity-1a1a1a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAulOtGdm3Ddx79vHsEgJWFq0n3AZWqdS4',
    appId: '1:750761744273:android:39daa1b89686c34c926c30',
    messagingSenderId: '750761744273',
    projectId: 'fixcity-1a1a1a',
    storageBucket: 'fixcity-1a1a1a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjnJ7wVUQZwsUfHcceMJ0w-4Hx_LeANZE',
    appId: '1:750761744273:ios:d36264bfbbaa9068926c30',
    messagingSenderId: '750761744273',
    projectId: 'fixcity-1a1a1a',
    storageBucket: 'fixcity-1a1a1a.firebasestorage.app',
    iosBundleId: 'com.example.fixcity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjnJ7wVUQZwsUfHcceMJ0w-4Hx_LeANZE',
    appId: '1:750761744273:ios:d36264bfbbaa9068926c30',
    messagingSenderId: '750761744273',
    projectId: 'fixcity-1a1a1a',
    storageBucket: 'fixcity-1a1a1a.firebasestorage.app',
    iosBundleId: 'com.example.fixcity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCofDK6y-2s1qjBPGuwLSW299C2oNT4OQ',
    appId: '1:750761744273:web:effd7021825c0c2e926c30',
    messagingSenderId: '750761744273',
    projectId: 'fixcity-1a1a1a',
    authDomain: 'fixcity-1a1a1a.firebaseapp.com',
    storageBucket: 'fixcity-1a1a1a.firebasestorage.app',
  );
}
