// lib/main.dart
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // This file was generated by `flutterfire configure`

// Import your pages
import 'home_page.dart'; // We will create this
import 'report_page.dart';
import 'track_page.dart';
import 'admin/admin_login_page.dart'; // Admin page
import 'admin/admin_dashboard_page.dart'; // Admin page
import 'admin/report_details_page.dart'; // Admin page

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  // Initialize Firebase
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'منصة البلاغات الموحدة',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blue,
        fontFamily: 'Cairo', // You can add a custom Arabic font
      ),
      // We set the text direction for the whole app
      builder: (context, child) {
        return Directionality(
          textDirection: TextDirection.rtl,
          child: child!,
        );
      },
      
      // Here we define all the "pages" (routes) in your application
      initialRoute: '/',
      routes: {
        // --- Mobile App Routes ---
        '/': (context) => const HomePage(),
        '/report': (context) => const ReportPage(),
        '/track': (context) => const TrackPage(),

        // --- Web Admin Panel Routes ---
        '/admin': (context) => const AdminLoginPage(),
        '/admin/dashboard': (context) => const AdminDashboardPage(),
        // We'll also have a dynamic route for report details
        // We will handle this in the AdminDashboardPage
      },
      // This handles dynamic routes like /admin/report/XYZ
      onGenerateRoute: (settings) {
        if (settings.name != null &&
            settings.name!.startsWith('/admin/report/')) {
          final reportId = settings.name!.split('/').last;
          return MaterialPageRoute(
            builder: (context) => ReportDetailsPage(reportId: reportId),
          );
        }
        return null; 
      },
    );
  }
}